new button to close connection
Kennox/rscc pull request #167
Opened 2017-05-27 13:24 UTC by Gyssim

2017-05-27 22:17 UTC, l-marchesi requested changes
Some smallers things to clarify, will boot into Lernstick and check how it looks

2017-05-27 22:17 UTC, l-marchesi commented on src/ch/imedias/rsccfx/localization/Strings.java
> + *  Code generated at 10:14:06 27.05.2017
Not quite sure but shouldn't this file be excluded from pushing?
@martinfrancois 
If so, please delete it :)

2017-05-27 22:17 UTC, l-marchesi commented on src/ch/imedias/rsccfx/view/RsccRequestPresenter.java
> -    view.generatedKeyFld.prefWidthProperty().bind(scene.widthProperty()
Did this get delete by you or by merging it from develop?

2017-05-27 22:17 UTC, l-marchesi commented on src/ch/imedias/rsccfx/view/RsccRequestView.java
> -  private Pane emptyPane = new Pane();
It seems a bit weird to me, that the pane is "lost"... Don't we need it to ensure a good looking gui? @JenniferMue & @martinfrancois

2017-05-28 13:43 UTC, Gyssim commented on src/ch/imedias/rsccfx/view/RsccRequestView.java
> -  private Pane emptyPane = new Pane();
It looked the same without the empty pane. I had an issue that the empty Pane overlapped my button, so I asked Francois and he said I can delete it

2017-05-28 14:53 UTC, l-marchesi commented on src/ch/imedias/rsccfx/view/RsccRequestView.java
> -  private Pane emptyPane = new Pane();
Okay, great! then it is alright :)

2017-05-28 14:53 UTC, l-marchesi commented
Did fix checkstyle errors. Now checking if it looks good

2017-05-28 15:18 UTC, l-marchesi commented
I tried to establish a connection between two of my computers, but it does not work. When changing back to branch develop it does. So something seems to be wrong on this branch.

2017-05-28 15:23 UTC, l-marchesi commented
Okay, forget about my last comment.
I did redo all the steps I did before and it works now. However, really strange.

2017-05-28 15:27 UTC, l-marchesi approved these changes

2017-05-28 15:40 UTC, merged